apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-lecture-backend
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/video-lecture-backend
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
